name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          # حل مشكلة المكتبات الناقصة في ubuntu 24.04
          wget http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb
          wget http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb
          sudo apt install ./libtinfo5_6.4-2_amd64.deb ./libncurses5_6.4-2_amd64.deb
          
          sudo apt install -y build-essential git python3-dev zip unzip openjdk-17-jdk libffi-dev libssl-dev
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer kivy

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DebtApp-Release-APK
          path: bin/*.apk
